spring:
  datasource:
    dynamic:
      enabled: true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      p6spy: true
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/sparkzxl_workflow
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        master1:
          url: jdbc:mysql://127.0.0.1:3306/sparkzxl_workflow
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql