system:
  name: Sparkzxl Auth
sparkzxl:
  data:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: sparkzxl_oauth
    enable-tenant: false
    p6spy: true
jwt:
  key-store:
    enable: true
    path: jwt.jks
    alias: jwt
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.sparkzxl.oauth.infrastructure.entity
  custom:
    mapper-scan: com.github.sparkzxl.oauth.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
knife4j:
  enable: true
  description: 授权认证在线文档
  base-package: com.github.sparkzxl.oauth.interfaces
  group: 授权认证应用
  title: 授权认证在线文档
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  license-url: https://github.com/sparkzxl
  contact:
    name: zhouxinlei
    email: zhouxinlei298@163.com
    url: https://github.com/sparkzxl
  global-operation-parameters:
    - name: Authorization
      description: 认证信息
      modelRef: String
      parameterType: header
      required: true
      defaultValue: "Bearer enVpaG91X3VpOnp1aWhvdV91aV9zZWNyZXQ="
security:
  csrf: false
  ignorePatterns:
    - /oauth/**
    - /authentication/**
    - /logout
    - /rsa/publicKey
  ignoreStaticPatterns:
    - /css/**
    - /images/**
    - /jquery/**
    - /js/**
open:
  app-id: sparkzxl
  sso-server-uri: http://127.0.0.1:8806
  logout: http://172.34.67.112:8806/logout