oss:
  enabled: true
  path-style-access: false
  endpoint: oss-cn-hangzhou.aliyuncs.com
  custom-domain: https://www.demo.com
  region: cn_north_1
  accessKey: 86af25253b5e438782b21365e61421b0
  secretKey: 4d3cb24c11ab477f803d2489da23216c
sparkzxl:
  data:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: sparkzxl_file
    p6spy: true
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.sparkzxl.file.infrastructure.entity
  custom:
    mapper-scan: com.github.sparkzxl.file.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
knife4j:
  enable: true
  group: 文件存储应用
  base-package: com.github.sparkzxl.file.interfaces
  title: 文件存储应用
  description: 文件存储管理
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  licenseUrl: https://github.com/sparkzxl
  contact:
    url: https://github.com/sparkzxl
    name: zhouxinlei
    email: zhouxinlei298@163.com
  global-operation-parameters:
    - name: Authorization
      description: 客户端信息
      modelRef: String
      parameterType: header
      required: true
      defaultValue: "Bearer enVpaG91X3VpOnp1aWhvdV91aV9zZWNyZXQ="