server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
knife4j:
  enable: true
  description: IDS Oauth2.0 授权在线文档
  base-package: com.github.sparkzxl.ids.interfaces
  group: IDS Oauth2.0授权应用
  title: IDS Oauth2.0 授权在线文档
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  license-url: https://github.com/sparkzxl
  contact:
    name: zhouxinlei
    email: zhouxinlei298@163.com
    url: https://github.com/sparkzxl
  global-operation-parameters:
    - name: Authorization
      description: 认证信息
      modelRef: String
      parameterType: header
      required: true
      defaultValue: "Bearer enVpaG91X3VpOnp1aWhvdV91aV9zZWNyZXQ="